---
title: "admixture_analysis"
author: "Yingxin Su"
date: "1/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load the package 

```{r}
library(viridis)
library(ggplot2) 
library(scales) 
library(dplyr) 
library(tidyr)
library(forcats)
library(plotly) 
library(RColorBrewer)
library(cowplot)
```

#Load the data 

```{r}
metad <-read.csv("metadata_spk_reord.csv",as.is=F, header=T)
qlist2 <- read.table("wh_2_output_reord.qopt")
qlist3 <- read.table("wh_3_output_reord.qopt", header=F)
qlist4 <- read.table("wh_4_reord.qopt", header=F)
qlist <- read.table("wh_5_reord.txt", header=F)#K=5
qlist6 <- read.table("wh_6_output_reord.qopt", header=F)
qlist7 <- read.table("wh_7_output_reord.qopt", header=F)
qlist8 <- read.table("wh_8_output_reord.qopt", header=F)
qlist9 <- read.table("wh_9_output_reord.qopt", header=F)
qlist[1,1] <- 1.00E-09
qlist <- as.data.frame(lapply(qlist, as.numeric))
```

#Rename the columns and edit the content in metadata 

```{r}
colnames(metad)[1] = "FID"
colnames(metad)[2] = "Species"
colnames(metad)[3] = "LOCATION"
#metad$Species <- gsub("_", " ", metad$Species)
#metad$Species <- gsub("Speckled Dace", "SD", metad$Species)
#metad$Species <- gsub("Santa Ana SD", "Santa Ana", metad$Species)
#metad$LOCATION <- gsub("Bonneville", "B",metad$LOCATION)
#metad$LOCATION <- gsub("SouthernCAC", "SCACoast",metad$LOCATION)
```


#bind the data 

```{r}
admix2 <- cbind(metad,qlist2)
admix3 <- cbind(metad,qlist3)
admix4 <- cbind(metad,qlist4)
admix <- cbind(metad,qlist)
admix6 <- cbind(metad,qlist6)
admix7 <- cbind(metad,qlist7)
admix8 <- cbind(metad,qlist8)
admix9 <- cbind(metad,qlist9)
```

#rename the column

```{r}
#admix2
colnames(admix2)[7] = "cluster1"
colnames(admix2)[8] = "cluster2"
#admix3
colnames(admix3)[7] = "cluster1"
colnames(admix3)[8] = "cluster2"
colnames(admix3)[9] = "cluster3"
#admix4
colnames(admix4)[7] = "cluster1"
colnames(admix4)[8] = "cluster2"
colnames(admix4)[9] = "cluster3"
colnames(admix4)[10] = "cluster4"
#admix(5)
colnames(admix)[7] = "cluster1"
colnames(admix)[8] = "cluster2"
colnames(admix)[9] = "cluster3"
colnames(admix)[10] = "cluster4"
colnames(admix)[11] = "cluster5"
#admix6
colnames(admix6)[7] = "cluster1"
colnames(admix6)[8] = "cluster2"
colnames(admix6)[9] = "cluster3"
colnames(admix6)[10] = "cluster4"
colnames(admix6)[11] = "cluster5"
colnames(admix6)[12] = "cluster6"
#admix7
colnames(admix7)[7] = "cluster1"
colnames(admix7)[8] = "cluster2"
colnames(admix7)[9] = "cluster3"
colnames(admix7)[10] = "cluster4"
colnames(admix7)[11] = "cluster5"
colnames(admix7)[12] = "cluster6"
colnames(admix7)[13] = "cluster7"
#admix8
colnames(admix8)[7] = "cluster1"
colnames(admix8)[8] = "cluster2"
colnames(admix8)[9] = "cluster3"
colnames(admix8)[10] = "cluster4"
colnames(admix8)[11] = "cluster5"
colnames(admix8)[12] = "cluster6"
colnames(admix8)[13] = "cluster7"
colnames(admix8)[14] = "cluster8"
#admix9 
colnames(admix9)[7] = "cluster1"
colnames(admix9)[8] = "cluster2"
colnames(admix9)[9] = "cluster3"
colnames(admix9)[10] = "cluster4"
colnames(admix9)[11] = "cluster5"
colnames(admix9)[12] = "cluster6"
colnames(admix9)[13] = "cluster7"
colnames(admix9)[14] = "cluster8"
colnames(admix9)[15] = "cluster9"
```

#mutate and reorder 
```{r}
#admix2 
admix_gg2 <- admix2 %>% gather(key = clustname, value = "clust", cluster1:cluster2) %>% 
  arrange(clustname, clust) %>% 
  mutate(
    SPP_ID3 = fct_reorder2(as.factor(FID), SUBREGION, clust),
    Location = fct_reorder2(as.factor(SUBREGION), clustname, clust),
    clustname = fct_reorder2(factor(clustname, levels = c("cluster1", "cluster2")), clustname, clust),
    
  ) %>% group_by(SUBREGION)
admix_gg2$location_reord <- factor(admix_gg2$LOCATION, levels = c("AMR","OWE", "LV", "LAH", "KLA", "SAC", "CCA", "BUT", "WAR", "B","WA","CLB", "CO","ANA" ) )
admix_gg2$species_reord <- factor(admix_gg2$Species, levels = c("Amargosa", "Owens", "Long Valley", "Lahontan", "Klamath", "Sacramento", "Not Designated", "Santa Ana"))
admix_gg2$SPP_ID <- fct_reorder2(as.factor(admix_gg2$SPP_ID3),admix_gg2$location_reord,admix_gg2$species_reord)
```

```{r}
admix_gg3 <- admix3 %>% gather(key = clustname, value = "clust", cluster1:cluster3) %>% 
  arrange(clustname, clust) %>% 
  mutate(
    SPP_ID3 = fct_reorder2(as.factor(FID), SUBREGION, clust),
    Location = fct_reorder2(as.factor(SUBREGION), clustname, clust),
    clustname = fct_reorder2(factor(clustname, levels = c("cluster1", "cluster2", "cluster3")), clustname, clust),
    
  ) %>% group_by(SUBREGION)
admix_gg3$location_reord <- factor(admix_gg3$LOCATION, levels = c("AMR","OWE", "LV", "LAH", "KLA", "SAC", "CCA", "BUT", "WAR", "B","WA","CLB", "CO","ANA" ))
admix_gg3$species_reord <- factor(admix_gg3$Species, levels = c("Amargosa", "Owens", "Long Valley", "Lahontan", "Klamath", "Sacramento", "Not Designated", "Santa Ana"))
```

```{r}
admix_gg4 <- admix4 %>% gather(key = clustname, value = "clust", cluster1:cluster4) %>% 
  arrange(clustname, clust) %>% 
  mutate(
    SPP_ID3 = fct_reorder2(as.factor(FID), SUBREGION, clust),
    Location = fct_reorder2(as.factor(SUBREGION), clustname, clust),
    clustname = fct_reorder2(factor(clustname, levels = c("cluster1", "cluster2", "cluster3","cluster4")), clustname, clust),
    
  ) #%>% group_by(SUBREGION)
admix_gg4$location_reord <- factor(admix_gg4$LOCATION,levels = c("AMR","OWE", "LV", "LAH", "KLA", "SAC", "CCA", "BUT", "WAR", "B","WA","CLB", "CO","ANA" ))
admix_gg4$species_reord <- factor(admix_gg4$Species, levels = c("Amargosa", "Owens", "Long Valley", "Lahontan", "Klamath", "Sacramento", "Not Designated", "Santa Ana"))
admix_gg4$SPP_ID <- fct_reorder2(as.factor(admix_gg4$SPP_ID3),admix_gg4$location_reord,admix_gg4$species_reord)
admix_gg4$SPP_ID1 <- fct_reorder2(as.factor(admix_gg4$SPP_ID3), admix_gg4$location_reord, admix_gg4$SUBREGION)
```

```{r}
admix_gg <- admix %>% gather(key = clustname, value = "clust", cluster1:cluster5) %>% 
  arrange(clustname, clust) %>% 
  mutate(
    SPP_ID3 = fct_reorder2(as.factor(FID), SUBREGION, clust),
    Location = fct_reorder2(as.factor(SUBREGION), clustname, clust),
    clustname = fct_reorder2(factor(clustname, levels = c("cluster1", "cluster2", "cluster3","cluster4", "cluster5")), clustname, clust),
    
  ) %>% group_by(SUBREGION)
admix_gg$location_reord <- factor(admix_gg$LOCATION, levels = c("AMR","OWE", "LV", "LAH", "KLA", "SAC", "CCA", "BUT", "WAR", "B","WA","CLB", "CO","ANA" ))
admix_gg$species_reord <- factor(admix_gg$Species, levels = c("Amargosa", "Owens", "Long Valley", "Lahontan", "Klamath", "Sacramento", "Not Designated", "Santa Ana"))

admix_gg$SPP_ID <- fct_reorder2(as.factor(admix_gg$SPP_ID3),admix_gg$location_reord,admix_gg$species_reord)
admix_gg$SPP_ID1 <- fct_reorder2(as.factor(admix_gg$SPP_ID3), admix_gg$location_reord, admix_gg$SUBREGION)
```

```{r}

admix_gg6 <- admix6 %>% gather(key = clustname, value = "clust", cluster1:cluster6) %>% 
  arrange(clustname, clust) %>% 
  mutate(
    SPP_ID3 = fct_reorder2(as.factor(FID), SUBREGION, clust),
    Location = fct_reorder2(as.factor(SUBREGION), clustname, clust),
    clustname = fct_reorder2(factor(clustname, levels = c("cluster1", "cluster2", "cluster3","cluster4", "cluster5", "cluster6")), clustname, clust),
    
  ) %>% group_by(SUBREGION) 
admix_gg6$location_reord <- factor(admix_gg6$LOCATION, levels = c("AMR","OWE", "LV", "LAH", "KLA", "SAC", "CCA", "BUT", "WAR", "B","WA","CLB", "CO","ANA" ))
admix_gg6$species_reord <- factor(admix_gg6$Species, levels = c("Amargosa", "Owens", "Long Valley", "Lahontan", "Klamath", "Sacramento", "Not Designated", "Santa Ana"))
admix_gg6$SPP_ID <- fct_reorder2(as.factor(admix_gg6$SPP_ID3),admix_gg6$location_reord,admix_gg6$species_reord)
admix_gg6$SPP_ID1 <- fct_reorder2(as.factor(admix_gg6$SPP_ID3), admix_gg6$location_reord, admix_gg6$SUBREGION)

```

```{r}
admix_gg7 <- admix7 %>% gather(key = clustname, value = "clust", cluster1:cluster7) %>% 
  arrange(clustname, clust) %>% 
  mutate(
    SPP_ID3 = fct_reorder2(as.factor(FID), SUBREGION, clust),
    Location = fct_reorder2(as.factor(SUBREGION), clustname, clust),
    clustname = fct_reorder2(factor(clustname, levels = c("cluster1", "cluster2", "cluster3","cluster4", "cluster5", "cluster6","cluster7")), clustname, clust),
    
  ) %>% group_by(SUBREGION) 
admix_gg7$location_reord <- factor(admix_gg7$LOCATION, levels = c("AMR","OWE", "LV", "LAH", "KLA", "SAC", "CCA", "BUT", "WAR", "B","WA","CLB", "CO","ANA" ))
admix_gg7$species_reord <- factor(admix_gg7$Species, levels = c("Amargosa", "Owens", "Long Valley", "Lahontan", "Klamath", "Sacramento", "Not Designated", "Santa Ana"))
admix_gg7$SPP_ID <- fct_reorder2(as.factor(admix_gg7$SPP_ID3),admix_gg7$location_reord,admix_gg7$species_reord)
```

```{r}
admix_gg7 <- admix7 %>% gather(key = clustname, value = "clust", cluster1:cluster7) %>% 
  arrange(clustname, clust) %>% 
  mutate(
    SPP_ID3 = fct_reorder2(as.factor(FID), SUBREGION, clust),
    Location = fct_reorder2(as.factor(SUBREGION), clustname, clust),
    clustname = fct_reorder2(factor(clustname, levels = c("cluster1", "cluster2", "cluster3","cluster4", "cluster5", "cluster6","cluster7")), clustname, clust),
    
  ) %>% group_by(SUBREGION) 
admix_gg7$location_reord <- factor(admix_gg7$LOCATION, levels = c("AMR","OWE", "LV", "LAH", "KLA", "SAC", "CCA", "BUT", "WAR", "B","WA","CLB", "CO","ANA" ))
admix_gg7$species_reord <- factor(admix_gg7$Species, levels =c("Amargosa", "Owens", "Long Valley", "Lahontan", "Klamath", "Sacramento", "Not Designated", "Santa Ana"))
admix_gg7$SPP_ID <- fct_reorder2(as.factor(admix_gg7$SPP_ID3),admix_gg7$location_reord,admix_gg7$species_reord)
admix_gg7$SPP_ID1 <- fct_reorder2(as.factor(admix_gg7$SPP_ID3), admix_gg7$location_reord, admix_gg7$SUBREGION)
```

```{r}
admix_gg8 <- admix8 %>% gather(key = clustname, value = "clust", cluster1:cluster8) %>% 
  arrange(clustname, clust) %>% 
  mutate(
    SPP_ID3 = fct_reorder2(as.factor(FID), SUBREGION, clust),
    Location = fct_reorder2(as.factor(SUBREGION), clustname, clust),
    clustname = fct_reorder2(factor(clustname, levels = c("cluster1", "cluster2", "cluster3","cluster4", "cluster5", "cluster6","cluster7", "cluster8")), clustname, clust),
    
  ) %>% group_by(SUBREGION) 
admix_gg8$location_reord <- factor(admix_gg8$LOCATION, levels = c("AMR","OWE", "LV", "LAH", "KLA", "SAC", "CCA", "BUT", "WAR", "B","WA","CLB", "CO","ANA" ))
admix_gg8$species_reord <- factor(admix_gg8$Species, levels =c("Amargosa", "Owens", "Long Valley", "Lahontan", "Klamath", "Sacramento", "Not Designated", "Santa Ana"))
admix_gg8$SPP_ID <- fct_reorder2(as.factor(admix_gg8$SPP_ID3),admix_gg8$location_reord,admix_gg8$species_reord)
admix_gg8$SPP_ID1 <- fct_reorder2(as.factor(admix_gg8$SPP_ID3), admix_gg8$location_reord, admix_gg8$SUBREGION)
```



```{r}
admix_gg9 <- admix9 %>% gather(key = clustname, value = "clust", cluster1:cluster9) %>% 
  arrange(clustname, clust) %>% 
  mutate(
    SPP_ID3 = fct_reorder2(as.factor(FID), SUBREGION, clust),
    Location = fct_reorder2(as.factor(SUBREGION), clustname, clust),
    clustname = fct_reorder2(factor(clustname, levels = c("cluster1", "cluster2", "cluster3","cluster4", "cluster5", "cluster6","cluster7", "cluster8", "cluster9")), clustname, clust),
    
  ) %>% group_by(SUBREGION) 
admix_gg9$location_reord <- factor(admix_gg9$LOCATION, levels = c("AMR","OWE", "LV", "LAH", "KLA", "SAC", "CCA", "BUT", "WAR", "B","WA","CLB", "CO","ANA" ))
admix_gg9$species_reord <- factor(admix_gg9$Species, levels = c("Amargosa", "Owens", "Long Valley", "Lahontan", "Klamath", "Sacramento", "Not Designated", "Santa Ana"))
admix_gg9$SPP_ID <- fct_reorder2(as.factor(admix_gg9$SPP_ID3),admix_gg9$location_reord,admix_gg9$species_reord)
admix_gg9$SPP_ID1 <- fct_reorder2(as.factor(admix_gg9$SPP_ID3), admix_gg9$location_reord, admix_gg9$SUBREGION)
```

#Plot

```{r}
#K = 2 
(plot2 <- admix_gg2 %>% 
    ggplot() + geom_col(aes(x=SPP_ID3, y=clust, fill=clustname), width = 1) + 
    scale_x_discrete(expand=c(0,0)) + 
    scale_y_continuous(expand=c(0,0)) +
    scale_fill_manual(name="Cluster",
                      values=c("#6bc5d2","#e3c878","#e688a1","#ffba92","#d6e4aa"),
                      labels=c("cluster1", "cluster2", "cluster3","cluster4", "cluster5"))+
    theme_classic(base_size = 10) +
    theme(axis.text.x = element_text(angle = 80, hjust = 0.5, size = 7)) +
    labs(x="", y="K = 2") +
    facet_grid(.~location_reord, scales = "free_x", space = "free_x") +
    theme(strip.background = element_blank(), 
          strip.text = element_text(size = 10, face = "bold"),
          panel.spacing = unit(0, "lines"),
          panel.border = element_rect(fill = NA, color = "gray10"),
          axis.title.y = element_text(size = 12, face = "bold"),
          axis.text.x=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.x=element_blank(),
          axis.ticks.y=element_blank(),
          legend.position = "none")) 
#K=3
(plot3 <- admix_gg3 %>% 
    ggplot() + geom_col(aes(x=SPP_ID3, y=clust, fill=clustname), width = 1) + 
    scale_x_discrete(expand=c(0,0)) + 
    scale_y_continuous(expand=c(0,0)) +
    scale_fill_manual(name="Cluster",
                      values=c("#6bc5d2","#e688a1","#e3c878"),
                      labels=c("cluster1", "cluster2", "cluster3","cluster4", "cluster5"))+
    theme_classic(base_size = 10) +
    theme(axis.text.x = element_text(angle = 80, hjust = 0.5, size = 7)) +
    labs(x="", y="K = 3") +
    facet_grid(.~location_reord, scales = "free_x", space = "free_x") +
    theme(strip.background = element_blank(), 
          strip.text.x = element_blank(),
          panel.spacing = unit(0, "lines"),
          panel.border = element_rect(fill = NA, color = "gray10"),
          axis.title.y = element_text(size = 12, face = "bold"),
          axis.text.x=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.x=element_blank(),
          axis.ticks.y=element_blank(),
          legend.position = "none")) 
#K=4
(plot4 <- admix_gg4 %>% 
    ggplot() + geom_col(aes(x=SPP_ID1, y=clust, fill=clustname), width = 1) + 
    scale_x_discrete(expand=c(0,0)) + 
    scale_y_continuous(expand=c(0,0)) +
    scale_fill_manual(name="Cluster",
                      values=c("#e688a1","#e3c878","#6bc5d2","#ffba92"),
                      labels=c("cluster1", "cluster2", "cluster3","cluster4"))+
    theme_classic(base_size = 10) +
    theme(axis.text.x = element_text(angle = 80, hjust = 0.5, size = 7)) +
    labs(x="", y="K = 4") +
    facet_grid(.~location_reord, scales = "free_x", space = "free_x") +
    theme(strip.background = element_blank(), 
          strip.text.x = element_blank(),
          panel.spacing = unit(0, "lines"),
          panel.border = element_rect(fill = NA, color = "gray10"),
          axis.title.y = element_text(size = 12, face = "bold"),
          axis.text.x=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.x=element_blank(),
          axis.ticks.y=element_blank(),
          legend.position = "none")) 
#K=5
(plot <- admix_gg %>% 
    ggplot() + geom_col(aes(x=SPP_ID1, y=clust, fill=clustname), width = 1) + 
    scale_x_discrete(expand=c(0,0)) + 
    scale_y_continuous(expand=c(0,0)) +
    scale_fill_manual(name="Cluster",
                      values=c("#e3c878","#e688a1","#6bc5d2","#d6e4aa","#ffba92"),
                      labels=c("cluster1", "cluster2", "cluster3","cluster4", "cluster5"))+
    theme_classic(base_size = 10) +
    theme(axis.text.x = element_text(angle = 80, hjust = 0.5, size = 7)) +
    labs(x="", y="K = 5") +
    facet_grid(.~location_reord, scales = "free_x", space = "free_x") +
    theme(strip.background = element_blank(), 
          strip.text.x = element_blank(),
          panel.spacing = unit(0, "lines"),
          panel.border = element_rect(fill = NA, color = "gray10"),
          axis.title.y = element_text(size = 12, face = "bold"),
          axis.text.x=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.x=element_blank(),
          axis.ticks.y=element_blank(),
          legend.position = "none"
          )) 
#K=6
(plot6 <- admix_gg6 %>% 
    ggplot() + geom_col(aes(x=SPP_ID1, y=clust, fill=clustname), width = 1) + 
    scale_x_discrete(expand=c(0,0)) + 
    scale_y_continuous(expand=c(0,0)) +
    scale_fill_manual(name="Cluster",
                      values=c("#e688a1","#d6e4aa","#6bc5d2","#ffba92","#e3c878","#9088d4"),
                      labels=c("cluster1", "cluster2", "cluster3","cluster4", "cluster5", "cluster6"))+
    theme_classic(base_size = 10) +
    theme(axis.text.x = element_text(angle = 80, hjust = 0.5, size = 7)) +
    labs(x="", y="K = 6") +
    facet_grid(.~location_reord, scales = "free_x", space = "free_x") +
    theme(strip.background = element_blank(), 
          strip.text.x = element_blank(),
          panel.spacing = unit(0, "lines"),
          panel.border = element_rect(fill = NA, color = "gray10"),
          axis.title.y = element_text(size = 12, face = "bold"),
          axis.text.x=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.x=element_blank(),
          axis.ticks.y=element_blank(),
          legend.position = "none"
          )) 

```
#text
```{r}
text <- admix_gg2 %>% ggplot(aes(x = SPP_ID, y = "")) + #geom_tile( color = "black", aes (fill = sub)) +
  facet_grid(.~species_reord, scale = "free", space = "free") + labs(x = "", y = "") + scale_x_discrete(expand=c(0,0)) +#scale_fill_viridis_d() +
  theme(legend.position = "bottom")  + theme(legend.position = "none") + 
  theme(panel.spacing=unit(0.02, "lines"),
        #panel.border = element_rect(colour = "black"),
        axis.text.x=element_blank(), 
        axis.text.y= element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank())+
  theme(strip.text = element_text(size = 11, face = "bold.italic"),
        strip.background = element_blank(),
      ) + theme(plot.margin=unit(c(0,0,0,0),"cm"))
text
```
#combine them together

```{r}
label <- c("K=2", "K=3", "K=4","K=5", "K=6")
p1 <- plot_grid(plot2, plot3, plot4, plot, plot6, nrow =5, rel_heights = c(1.8,1.5,1.5,1.5,1.5), axis = "lr", align = "v")
p1

```

#Supplement figures (K=7-9)

```{r}
(plot7 <- admix_gg7 %>% 
    ggplot() + geom_col(aes(x=SPP_ID1, y=clust, fill=clustname), width = 1) + 
    scale_x_discrete(expand=c(0,0)) + 
    scale_y_continuous(expand=c(0,0)) +
    scale_fill_manual(name="Cluster",
                      values=c("#cc7351","#6bc5d2","#d6e4aa","#ffba92","#9088d4","#e3c878","#e688a1"),
                      labels=c("cluster1", "cluster2", "cluster3","cluster4", "cluster5", "cluster6", "cluster7"))+
    theme_classic(base_size = 10) +
    theme(axis.text.x = element_text(angle = 80, hjust = 0.5, size = 7)) +
    labs(x="", y="K = 7") +
    facet_grid(.~location_reord, scales = "free_x", space = "free_x") +
    theme(strip.background = element_blank(), 
          #strip.text.x = element_blank(),
          strip.text = element_blank(),
          axis.title.y = element_text(size = 12, face = "bold"),
          panel.spacing = unit(0, "lines"),
          panel.border = element_rect(fill = NA, color = "gray10"),
          axis.text.x=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.x=element_blank(),
          axis.ticks.y=element_blank(),
          legend.position = "none"
          )) 

```
```{r}
(plot8 <- admix_gg8 %>% 
    ggplot() + geom_col(aes(x=SPP_ID1, y=clust, fill=clustname), width = 1) + 
    scale_x_discrete(expand=c(0,0)) + 
    scale_y_continuous(expand=c(0,0)) +
    scale_fill_manual(name="Cluster",
                      values=c("#9088d4","#d6e4aa","#6bc5d2","#ffba92","#e688a1","#e3c878", "#cc7351","#a9294f"),
                      labels=c("cluster1", "cluster2", "cluster3","cluster4", "cluster5", "cluster6", "cluster7", "cluster8"))+
    theme_classic(base_size = 10) +
    theme(axis.text.x = element_text(angle = 80, hjust = 0.5, size = 7)) +
    labs(x="", y="K = 8") +
    facet_grid(.~location_reord, scales = "free_x", space = "free_x") +
    theme(strip.background = element_blank(), 
          strip.text.x = element_blank(),
          #strip.text = element_text(size = 10, face = "bold"),
          axis.title.y = element_text(size = 12, face = "bold"),
          panel.spacing = unit(0, "lines"),
          panel.border = element_rect(fill = NA, color = "gray10"),
          axis.text.x=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.x=element_blank(),
          axis.ticks.y=element_blank(),
          legend.position = "none"
          )) 
```
```{r}
(plot9 <- admix_gg9 %>% 
    ggplot() + geom_col(aes(x=SPP_ID1, y=clust, fill=clustname), width = 1) + 
    scale_x_discrete(expand=c(0,0)) + 
    scale_y_continuous(expand=c(0,0)) +
    scale_fill_manual(name="Cluster",
                      values=c("#cc7351","#a9294f","#ffba92","#e688a1","#9088d4","#6bc5d2","#d6e4aa","#a6a9b6","#e3c878" ),
                      labels=c("cluster1", "cluster2", "cluster3","cluster4", "cluster5", "cluster6", "cluster7", "cluster8", "cluster9"))+
    theme_classic(base_size = 10) +
    theme(axis.text.x = element_text(angle = 80, hjust = 0.5, size = 7)) +
    labs(x="", y="K = 9") +
    facet_grid(.~location_reord, scales = "free_x", space = "free_x") +
    theme(strip.background = element_blank(), 
          strip.text.x = element_blank(),
          #strip.text = element_text(size = 10, face = "bold"),
          panel.spacing = unit(0, "lines"),
          panel.border = element_rect(fill = NA, color = "gray10"),
          axis.title.y = element_text(size = 12, face = "bold"),
          axis.text.x=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.x=element_blank(),
          axis.ticks.y=element_blank(),
          legend.position = "none"
          )) 
```
#put them together

```{r}
label1 <- c("K=7", "K=8", "K=9")
s1 <- plot_grid(plot2, plot3, plot4, plot, plot6,plot7, plot8, plot9, nrow =8, rel_heights = c(1.3,1,1,1,1,1,1,1), axis = "lr", align = "v")
                #labels = label1,
                #label_size = 9, vjust=9, hjust=-0.1)
s1
```



#backup

```{r}
(plot6a <- admix_gg6 %>% 
    ggplot() + geom_col(aes(x=SPP_ID3, y=clust, fill=clustname)) + 
    scale_x_discrete(expand=c(0,0)) + 
    scale_y_continuous(expand=c(0,0)) +
    scale_fill_manual(name="Cluster",
                      values=c("#6bc5d2","#e3c878","#e688a1","#ffba92","#d6e4aa","#9088d4"),
                      labels=c("cluster1", "cluster2", "cluster3","cluster4", "cluster5", "cluster6"))+
    theme_classic(base_size = 10) +
    theme(axis.text.x = element_text(angle = 80, hjust = 0.5, size = 7)) +
    labs(x="", y="") +
    facet_grid(.~location_reord, scales = "free_x", space = "free_x") +
    theme(strip.background = element_blank(), 
          strip.text.x = element_blank(),
          panel.spacing = unit(0, "lines"),
          panel.border = element_rect(fill = NA, color = "gray40"),
          axis.text.x=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.x=element_blank(),
          axis.ticks.y=element_blank(),
          legend.position = "top",
          legend.title = element_blank()
          )) 
legend <- get_legend(plot6a)
legend
plot_grid(legend)
plot_grid(legend,p1, nrow = 2, rel_heights=c(0.05,1))
```

#figure1B
```{r}
(plot3a <- admix_gg3 %>% 
    ggplot() + geom_col(aes(x=SPP_ID3, y=clust, fill=clustname),width=1) + 
    scale_x_discrete(expand=c(0,0)) + 
    scale_y_continuous(expand=c(0,0)) +
    scale_fill_manual(name="Cluster",
                      values=c("#6bc5d2","#e688a1","#e3c878"),
                      labels=c("cluster1", "cluster2", "cluster3","cluster4", "cluster5"))+
    theme_classic(base_size = 10) +
    theme(axis.text.x = element_text(angle = 80, hjust = 0.5, size = 7)) +
    labs(x="", y="K = 3") +
    facet_grid(.~location_reord, scales = "free_x", space = "free_x") +
    theme(strip.background = element_blank(), 
          strip.text = element_text(size = 11, face = "bold"),
          #strip.text.x = element_blank(),
          panel.spacing = unit(0, "lines"),
          panel.border = element_rect(fill = NA, color = "gray10"),
          axis.text.x=element_blank(),
          axis.text.y=element_blank(),
          axis.title.y = element_text(size = 12, face = "bold"),
          axis.ticks.x=element_blank(),
          axis.ticks.y=element_blank(),
          legend.position = "none")) 
plot3a
```

